title = "Alpaca Sample Driver (Rotator)"

[network]
addr_family = 'ipv4'        # Server answers on 'ipv4' or 'ipv6'
ip_address = ''             # Nominally any address ('' for ipv4 or '::1' for ipv6)
port = 5555

[server]
location = 'Anywhere on Earth'  # Anything you want here
verbose_driver_exceptions = true

[device]
can_reverse = true
step_size = 1.0
steps_per_sec = 6
sync_write_connected = true     # True to emulate sync Connected = true (for Conform)

[logging]
log_level = 'INFO'
log_to_stdout = false
max_size_mb = 5
num_keep_logs = 10
